Repository ashmanix/obs-plugin-countdown, pull requests merged in 2023-02, with the labels that each got.

#15 Add pt-BR translation
  data/locale/pt-BR.ini
Labels: enhancement

#13 Little changes for en-GB.ini
  data/locale/en-GB.ini
Labels: Improvement

#14 Add OUT OF TREE building
  CMakeLists.txt
Labels: Improvement

#16 Added en-US locale file that matches en-GB
  data/locale/en-US.ini
Labels: enhancement

#19 Removed unused SLOTs and added ability to save timer tab selected
  src/countdown-widget.cpp
Labels: bug, enhancement

#21 Added code that will create config folder if one doesn't exist
  src/countdown-widget.cpp
Labels: bug
