Repository ashmanix/obs-plugin-countdown, pull requests merged in 2024-11, with the labels that each got.

#67 Add Feature To Countdown In Days
  build-aux/.run-format.zsh
  data/locale/da-DK.ini
  data/locale/en-GB.ini
  data/locale/en-US.ini
  data/locale/pt-BR.ini
  src/CountdownTimer.ui
  src/countdown-widget.cpp
  src/countdown-widget.hpp
Labels: enhancement

#70 Add option to show leading zero
  data/locale/da-DK.ini
  data/locale/en-GB.ini
  data/locale/en-US.ini
  data/locale/pt-BR.ini
  images/fullScreenshot.png
  images/screenshotV2.png
  src/CountdownTimer.ui
  src/countdown-widget.cpp
  src/countdown-widget.hpp
Labels: enhancement

#72 Added additional hooks and state callbacks
  src/countdown-widget.cpp
  src/countdown-widget.hpp
Labels: enhancement

#78 Add Count Up Feature
  data/locale/da-DK.ini
  data/locale/en-GB.ini
  data/locale/en-US.ini
  data/locale/pt-BR.ini
  src/CountdownTimer.ui
  src/countdown-widget.cpp
  src/countdown-widget.hpp
  src/utils/timer-utils.cpp
  src/utils/timer-utils.hpp
Labels: enhancement

#79 Fix - Loaded date is before current date
  src/countdown-widget.cpp
Labels: bug

#80 Updated images
  images/fullScreenshot.png
  images/screenshotV2.png
  src/countdown-widget.cpp
Labels: documentation
