Repository ashmanix/obs-plugin-countdown, pull requests merged in 2025-01, with the labels that each got.

#111 Fixed name for timer tick event
  src/widgets/ashmanix-timer.cpp
Labels: bug

#115 Update translations to en-GB and pt-BR
  data/locale/en-GB.ini
  data/locale/pt-BR.ini
Labels: bug, enhancement

#116 Time left on timer is now saved and loaded for period time
  src/widgets/ashmanix-timer.cpp
  src/widgets/ashmanix-timer.hpp
Labels: enhancement

#118 Added feature where user can format timer output on counting
  data/locale/da-DK.ini
  data/locale/en-GB.ini
  data/locale/en-US.ini
  data/locale/pt-BR.ini
  src/ui/SettingsDialog.ui
  src/utils/timer-utils.hpp
  src/widgets/ashmanix-timer.cpp
  src/widgets/ashmanix-timer.hpp
  src/widgets/settings-dialog.cpp
  src/widgets/settings-dialog.hpp
Labels: enhancement

#120 Add Smooth Increment Option For Counting
  data/locale/da-DK.ini
  data/locale/en-GB.ini
  data/locale/en-US.ini
  data/locale/pt-BR.ini
  src/ui/SettingsDialog.ui
  src/utils/timer-utils.hpp
  src/widgets/ashmanix-timer.cpp
  src/widgets/settings-dialog.cpp
  src/widgets/settings-dialog.hpp
Labels: enhancement

#123 Added code to toggle the countdown type on load
  src/widgets/ashmanix-timer.cpp
Labels: bug
